### PR TITLE
Add tag for http status codes

### PR DESCRIPTION
**Pull request by oad-dwarf**
@themsaid here you go :-)

### CODE REVIEW

**Comment by themsaid** [comment]
You'll need to do it in the RequestWatcher itself, check the other watchers as an example.

**Comment by oad-dwarf** [comment]
Thank you, I have made the change.

**Comment by taylorotwell** [comment]
I don't want to tag on status code. It's just a very general tag.

**Comment by oad-dwarf** [comment]
Adding the http status code as a tag makes it easy to find requests that return 422 or 500 without scrolling a lot.

This is our use case, which I think is a very nice feature for a tool such as Telescope. Would you consider taking in this PR on that basis?

Or do you have plans for another way to search for requests on status code?

**Pull request closed without merging**
