### PR TITLE
[4.x] Make event watcher compatible with Laravel 8 subscriber syntax

### PR DESCRIPTION
**Pull request by paras-malhotra**
Fixes https://github.com/laravel/telescope/issues/952

### CODE REVIEW

**Comment by paras-malhotra** [comment]
Already fixed in https://github.com/laravel/telescope/commit/a69fc6f4f5fd5b0ac5a242981e162774cbb69e17

**Comment by themsaid** [comment]
@paras-malhotra can you re-open the PR with the tests?

**Comment by paras-malhotra** [comment]
Sure @themsaid, I've modified the PR with just the new tests.

**Comment by themsaid** [comment]
Thank you :)

**Pull request merged**
