### PR TITLE
Mark exceptions as resolved

### PR DESCRIPTION
**Pull request by barryvdh**
This allows to mark exceptions as resolved, and show warnings when not resolved.

image

image

If an Exception occurs again, it's shown as not-resolved again (because the last entry is shown, which is good).

### CODE REVIEW

**Comment by taylorotwell** [comment]
The button looks slightly too low. It's not vertically aligned with the text on the left.

**Comment by barryvdh** [comment]
Is this better?

image

**Comment by taylorotwell** [comment]
Hmm, it looks more aligned but now the top padding on the button appears much less than the bottom padding. Sorry I am picky about these things 😬

**Comment by barryvdh** [comment]
But isn't that exactly the same as the Auth tag? Tried using the built in styling classes.

**Comment by barryvdh** [comment]
Do you mean inside the button? Because the padding above the lowercase letters it the same top and bottom. Only the uppercase 'R' and 'l' are closer to the top. So not really sure how it should be aligned otherwise:
image

**Comment by GertjanRoke** [comment]
Maybe the `vertical-align` of the `.badge` class needs to be changed to `text-align: center;` that fixed it for me.

**Comment by taylorotwell** [comment]
@GertjanRoke can you screenshot that?

**Comment by GertjanRoke** [comment]
image
The right one is with `vertical-align: middle;`

**Comment by barryvdh** [comment]
I can change that, but that would be benifitial for all `.badge` items, so not sure if that's related to this PR.

**Comment by GertjanRoke** [comment]
@taylorotwell I thought I would make a better screenshot for you by rebuilding what @barryvdh had in his first screenshot.

So this one is with `vertical-align: bottom`:  

image

And this one is with `vertical-align: middle`:  

image

And this is with the current styling:  

image

Hope this makes it easier to decide what the best option is.

**Comment by taylorotwell** [comment]
I'll just go as-is for now.

**Comment by barryvdh** [comment]
Thanks, should I submit a PR to rebuild assets and perhaps tag a new release after that, to prepare for 6.0?

**Pull request merged**
