### PR TITLE
Revert upgrading highlight.js

### PR DESCRIPTION
**Pull request by sebdesign**

### CODE REVIEW

**Review by driesvints — APPROVED** [review]

**Comment by sebdesign** [comment]
I just install node v17 on my machine and it doesn't work, even with reverting this.

**Comment by driesvints** [comment]
hmm let's just revert the entire thing then for now.

**Comment by sebdesign** [comment]
I did revert the entire PR, and it still doesn't compile. :/

**Comment by driesvints** [comment]
Hmm I guess it doesn't have to do with your pr but I want to get to the bottom of why it suddenly doesn't compiles for me anymore. Thanks though!

**Comment by sebdesign** [comment]
No worries, I'll try to debug this also, since I can reproduce it.

**Pull request closed without merging**
