### PR TITLE
Add app_name in dashboard

### PR DESCRIPTION
**Pull request by tomswinkels**
We have a few project and every project has telescope. We have place the telescope monitor on a screen with a switch between all the telescopes but we now can't see witch telescope it is.

We think this is a good solution.

### CODE REVIEW

**Comment by browner12** [comment]
Environment variables should not be directly accessed in views. Please use a config variable instead.

**Comment by tomswinkels** [comment]
@browner12 Taylor always say not to much config variables?

**Comment by browner12** [comment]
If an application uses configuration caching, all calls to `env()` will return `null`.

https://laravel.com/docs/5.8/configuration#configuration-caching

**Comment by tomswinkels** [comment]
Thnx @browner12. What is the best place? config/telescope.php?

**Comment by browner12** [comment]
it already exists in `config/app.php`.

`config('app.name')`.

**Comment by tomswinkels** [comment]
You right. I have make a change in the pr.

**Pull request merged**
