### PR TITLE
[4.x] Added color highlighting of duplicate database queries

### PR DESCRIPTION
**Pull request by andrey-helldar**
Now the list of requests shows only the number of duplicate requests, and in order to find which ones are duplicated, you have to manually compare them.

I suggest highlighting entries containing duplicate requests.

#### Before
image

#### After
image
image

For issue https://github.com/laravel/telescope/issues/1326

### CODE REVIEW

**Comment by taylorotwell** [comment]
Sorry - still not in love with this. Will try to figure out something on my end.

**Comment by nurdism** [comment]
@taylorotwell, any updates on this? This would be a great addition to the telescope, it's been over a year, and nothing has been added. I'm running into having a hard time trying to figure out where/what my duplicated queries are, especially when there are more than 10-20 queries in a request or job. I'd be willing to re-add/expand on this PR but I don't see a point if it just gets left with a "not in love with this" and not any actual feedback that is actionable.

**Comment by Shadercloud** [comment]
Why is this not merged? Would be very useful.  For example find the duplicates here (it's not the insert jobs)....it's very difficult to find duplicates.

image

**Comment by andrey-helldar** [comment]
Apparently either very few people use Telescope, or no one looks at duplicate requests :)

**Pull request closed without merging**
