### PR TITLE
[5.x] Update to bootstrap 5.1 and drop jQuery

### PR DESCRIPTION
**Pull request by mmachatschek**
This PR updates bootstrap from 4.6 to 5.1 and applies the migration steps from https://getbootstrap.com/docs/5.1/migration/

Additionally I managed to remove jQuery and replace its usage with vanilla JS.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Converting this to draft while @themsaid reviews it. Please mark as ready once reviewed.

**Comment by themsaid** [comment]
Screen Shot 2022-02-10 at 5 31 58 PM

The header icons are out of place 

---

Screen Shot 2022-02-10 at 5 32 23 PM


Code blocks are overflowing

---

Other than these, everything looks ok.

**Comment by mmachatschek** [comment]
@themsaid the overflowing text in the json output is also a problem on the 4.x branch. Fixed it.

I found one missing utility class that had the wrong prefix.

The navigation is working fine on my side, can you try it again. After switching to the new branch I had to do a full reload with cache invalidation in the browser.

**Comment by mmachatschek** [comment]
@themsaid this is new since bootstrap v5 https://getbootstrap.com/docs/5.1/content/tables/ every table has a border under the table-head.

Should I remove it?
https://github.com/twbs/bootstrap/blob/a7942190c746b4aeefc5e7680cb396b1885670aa/scss/_tables.scss#L44

**Comment by taylorotwell** [comment]
Yes please remove that.

**Comment by driesvints** [comment]
We're very sorry @mmachatschek but we had to revert this PR because it majorly conflicted with https://github.com/laravel/telescope/pull/1295 in almost every Vue file. We decided to revert this one so we could merge 4.x into 5.x for preparation of Laravel v11 support. We're definitely still open to this PR but we'll need a fresh one.

**Pull request merged**
