### PR TITLE
[1.0] Add Gate watcher to record gate checks

### LINKED ISSUE #472: [Feature Request] Gate Watcher
It would be useful to have Gate watchers that record the gate abilities checked, user/guest and result. This can be done using the Gate afterCallbacks.

I would be happy to submit a PR if this is a welcome feature.

### PR DESCRIPTION
**Pull request by paras-malhotra**
This PR adds a Gate Watcher that allows us to record and monitor gate checks. I think this would be really helpful to understand which gate/permission checks are performed on requests and the result of those checks. The Gate Watcher is disabled by default to avoid breaking changes. Closes #472.

Screenshots below:

**Index Screen**

screen shot 2018-12-06 at 3 02 07 am

**Preview Screen (1/2)**

screen shot 2018-12-06 at 3 03 08 am

**Preview Screen (2/2)**

screen shot 2018-12-06 at 3 05 16 am

**Related Entries on Request Screen**

screen shot 2018-12-06 at 3 06 19 am

### CODE REVIEW

**Comment by taylorotwell** [comment]
Does this work with policies?

**Comment by paras-malhotra** [comment]
@taylorotwell yes, it works with policies as well. I've added policy tests to the `GateWatcherTest` class to confirm.

**Comment by paras-malhotra** [comment]
@themsaid thanks for merging. In your formatting commit, you've removed the `?Authenticatable` type hinting but this would be required for guest policies / gate checks to work.

**Comment by themsaid** [comment]
How?

**Comment by paras-malhotra** [comment]
This function checks for the type hints and only methods that have the type hint will be called for guest policies:

https://github.com/laravel/framework/blob/f2e14602e9601e2ddce3d597a72a2bcfb445b587/src/Illuminate/Auth/Access/Gate.php#L358-L382

**Comment by themsaid** [comment]
@paras-malhotra ah thanks, corrected :)

**Pull request merged**
