### PR TITLE
[3.x] Add afterStore hooks

### PR DESCRIPTION
**Pull request by barryvdh**
Add a hook for after the actual recording. This could be used for notifications etc, sending the actual Telescope URL in the mail/Slack message

```php
Telescope::afterStore(function(Telescope $telescope, $batchId) {

    foreach ($telescope::$entriesQueue as $entry) {
        if ($entry instanceof IncomingExceptionEntry) {
           dispatch(new TelescopeExceptionNotification($entry));
        }
    }
});
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Should we send the entries to this callback? It feels odd to have to dig into a static property of Telescope to access them.

**Comment by barryvdh** [comment]
Yeah sure, so entries first and then batchId? Not sure if the instance is needed, but that was more inline with the afterRecord one. Will change it

**Comment by taylorotwell** [comment]
Yeah I think that makes sense.

**Comment by barryvdh** [comment]
I've updated the signature and also moved the store/filter methods inside the 'without recording' block, because otherwise it would generate Entries for the store/updates (which were then never flushed anyway).

**Pull request merged**
