### PR TITLE
Added localization

### PR DESCRIPTION
**Pull request by andrey-helldar**
Added the ability to localize the interface.

For example, for French:

image

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by andrey-helldar** [comment]
@taylorotwell, may I ask why it is not possible to provide developers with the Telescope interface in their language?

We have a team of native speakers in the [`Laravel Lang`](https://github.com/Laravel-Lang/lang) project and we support translations of Laravel projects into 78 languages.

**Comment by darakanoit** [comment]
it would be interesting

**Comment by azzumed** [comment]
Awesome, it must be implemented! 🤩

**Pull request closed without merging**
