### PR TITLE
Travis already does self-update

### PR DESCRIPTION
**Pull request by szepeviktor**
Composer does not need self-update.
Plus some quote-normalization!

### CODE REVIEW

**Comment by paras-malhotra** [comment]
Any reason why the laravel framework has the same composer self-update?

**Comment by szepeviktor** [comment]
> Any reason why the laravel framework repo's travis file has the same composer self-update?

They may not spot the same command in Travis' log https://travis-ci.org/laravel/telescope/jobs/460436317#L480

**Comment by szepeviktor** [comment]
In the near past it was a problem with Travis.

**Comment by taylorotwell** [comment]
If nothing is broken I see no reason to change things.

**Pull request closed without merging**
