### PR TITLE
Fix duplicated queries on multiple connections

### PR DESCRIPTION
**Pull request by February30th**
Fixes duplicated query count when running same sql statement on multiple connections.

### CODE REVIEW

**Comment by February30th** [comment]
Fetching activity log of multiple databases:

```
SELECT * FROM activity_log; // connection: db-1
SELECT * FROM activity_log; // connection: db-2
```

The queries get flagged as duplicated, despite running in two different databases, which is not accurate.

**Comment by crynobone** [comment]
How does it handle the following?

```sql
SELECT * FROM activity_log; // connection: db-1
SELECT * FROM activity_log; // connection: db-2
SELECT * FROM activity_log; // connection: db-1
SELECT * FROM activity_log; // connection: db-2
SELECT * FROM activity_log; // connection: db-1
```

**Comment by zhoubiaobiao** [comment]
ignore_paths not work

return ! $request->is(
            collect([
                'telescope-api*',
                'vendor/telescope*',
                'horizon*',
                'vendor/horizon*',
            ])
                ->merge(config('telescope.ignore_paths', []))
                ->unless(is_null(config('telescope.path')), function ($paths) {
                    return $paths->prepend(config('telescope.path').'*');
                })
                ->all()
        );

change:

$ignore = collect([
            'telescope-api*',
            'vendor/telescope*',
            'horizon*',
            'vendor/horizon*',
        ])
            ->merge(config('telescope.ignore_paths', []))
            ->unless(is_null(config('telescope.path')), function ($paths) {
                return $paths->prepend(config('telescope.path').'*');
            })
            ->all();
        foreach ($ignore as $path) {
            if($request->is($path)) return true;
        }

**Comment by February30th** [comment]
5 duplicated queries, should be 3 duplicated queries (2 on connection db-1) and 1 duplicated query on db-2

**Comment by crynobone** [comment]
Wouldn't that make the change above invalid?

```
queries.length - size(...duplicates)

5 - size([2, 3]) = 3
```

**Comment by crynobone** [comment]
> 5 total queries, should be 3 duplicated queries (2 on connection db-1) and 1 duplicated query on db-2

This make sense.

**Review by crynobone — APPROVED** [review]

**Pull request merged**
