### PR TITLE
Add HTTP Client transfer time

### PR DESCRIPTION
**Pull request by zarulizham**
#1202

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by yurakulikov** [comment]
Why is the field transfer time not added in the Telescope HTTP client?
Because this is very important information for debugging and monitoring.

**Comment by zarulizham** [comment]
> Why is the field transfer time not added in the Telescope HTTP client?
> Because this is very important information for debugging and monitoring.

Hi, I agree with you. Perhaps @taylorotwell can change his mind to merge this one.

BTW, you can use forked version if you need the transfer time. 

https://github.com/zarulizham/telescope/tree/http-client-stat-compiled

In your composer.json

```
{
    ...
    ...
    "repositories: [{
          "type": "vcs",
          "url": "https://github.com/zarulizham/telescope.git"
    }],
    ...
    "require: {
         ...
         "laravel/telescope": "dev-http-client-stat-compiled",
         ...
    }
}

**Comment by yurakulikov** [comment]
@zarulizham, thx. At the moment I am recording the time in logs. But I would like to see the solution in the official telescope package.

**Comment by danilopinotti** [comment]
I made a "workaround" to show this info without need to edit Telescope Source code:
example

Code:
https://gist.github.com/danilopinotti/874afea1271106959c13a055720e3ca6

**Comment by yurakulikov** [comment]
@danilopinotti thx you for your solution. But I would still like to hear @taylorotwell  opinion. Because I see that this question bothers many.

**Comment by Saifallak** [comment]
looking forward for this feature too. +1

**Comment by IcedElect** [comment]
+1 @taylorotwell

**Pull request closed without merging**
