### PR TITLE
[1.0] Adds Larastan

### PR DESCRIPTION
**Pull request by nunomaduro**
This Pull Request adds [nunomaduro/larastan](http://github.com/nunomaduro/larastan) as `require-dev` dependency of Telescope. Larastan is a wrapper of PHPStan, and is a **static analysis** tool for PHP.

About Phpstan: "_PHPStan is a static analysis tool for PHP code. It parses your code and tries to find flaws in the program logic (like a variable being used before being declared, or a function being called that does not exist...). It is not the ultimate tool for catching bugs but it has one huge advantage: it does not need a lot work to set up! No need to write unit tests, simply run the tool and it will output a list of potential errors!_".

You can read more in this article: [medium.com/@ondrejmirtes/phpstan-2939cd0ad0e3](https://medium.com/@ondrejmirtes/phpstan-2939cd0ad0e3)

This **Pull Request also fixes the errors detected until level `1`**, later I will submit pull requests until we get level `>= 5`.

Usage:
```bash
./vendor/bin/phpstan analyse
```
example

Notes:
- You can choose from currently 8 levels: (0 is the loosest and 7 is the strictest) by passing `--level` option: `./vendor/bin/phpstan analyse --level=5`.
- **Larastan is not stable yet**. But I am using it in all my projects and packages.
- The line `./vendor/bin/phpstan analyse` should be added to `.travis.yml` in order to auto-analyse pull requests.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Looks like this PR has conflicts.

**Comment by nunomaduro** [comment]
@taylorotwell The conflicts are resolved.

**Comment by nunomaduro** [comment]
Wait a min.

**Comment by nunomaduro** [comment]
@taylorotwell There you go: https://github.com/laravel/telescope/pull/63

**Pull request closed without merging**
