### PR TITLE
Remove trimming of entries

### PR DESCRIPTION
**Pull request by themsaid**
If people want to remove older entries they should use the prune console command or implement their own scheduled job.

### CODE REVIEW

**Comment by deleugpn** [comment]
Running services behind a VPC on Amazon means I don't have an easy way of running Console commands since I cannot `ssh` into AWS Fargate and I also don't plan on having a container running 24/7 just to run Laravel Schedule. The simple pruning system was really good for GDPR compliance.
Do you plan on giving us anything similar again?

**Comment by themsaid** [comment]
@deleugpn you can run your own code in a terminable middleware, that's how trimming used to work.

**Comment by tillkruss** [comment]
Is this mentioned in the docs?

**Comment by paras-malhotra** [comment]
I've created a package for intelligent pruning: https://github.com/insenseanalytics/laravel-telescope-pruning

Comments/suggestions would be most appreciated!

**Pull request merged**
