### PR TITLE
add environments to config

### PR DESCRIPTION
**Pull request by MoatazAbdAlmageed**
I used telescope in project with multi environments , and I want to use telescope in multi environments so I added environments array in config

### CODE REVIEW

**Comment by MoatazAbdAlmageed** [comment]
I asked https://poe.com/ and I got this answer 

you can add those to telescope config file

```
 'environments' => [
        'local' => [
            'path' => '/telescope',
            'enabled' => true,
        ],
        'canary' => [
            'path' => '/telescope',
            'enabled' => true,
        ],
        'staging' => [
            'path' => '/telescope',
            'enabled' => true,
        ],
        'production' => [
            'enabled' => false,
        ],
    ],

```
if it works please mention this into docs

thanks

**Comment by MoatazAbdAlmageed** [comment]
> I asked https://poe.com/ and I got this answer
> 
> you can add those to telescope config file
> 
> ```
>  'environments' => [
>         'local' => [
>             'path' => '/telescope',
>             'enabled' => true,
>         ],
>         'canary' => [
>             'path' => '/telescope',
>             'enabled' => true,
>         ],
>         'staging' => [
>             'path' => '/telescope',
>             'enabled' => true,
>         ],
>         'production' => [
>             'enabled' => false,
>         ],
>     ],
> ```
> 
> if it works please mention this into docs
> 
> thanks

I got ErrorException: Array to string conversion 

so could you please accept my PR or suggest any solution ?

**Comment by MoatazAbdAlmageed** [comment]
@taylorotwell please let me know how can I use telescope in multi environments .. depending on api not web middleware?

**Comment by crynobone** [comment]
This has been described in the documentation: https://laravel.com/docs/10.x/telescope#dashboard-authorization

**Comment by MoatazAbdAlmageed** [comment]
> Member

Thank you but I'm using laravel for APi so how can I pass emails ? there is no login views?!

**Comment by MoatazAbdAlmageed** [comment]
> This has been described in the documentation: https://laravel.com/docs/10.x/telescope#dashboard-authorization

Thank you but I'm using laravel for APi so how can I pass emails ? there is no login views?!

**Pull request closed without merging**
