### PR TITLE
[4.x] Added isCommand() filter

### PR DESCRIPTION
**Pull request by Ali-Shaikh**
Determine if the incoming entry is an artisan command.

### CODE REVIEW

**Comment by taylorotwell** [comment]
The type property is public. You can already inspect it.

**Comment by Ali-Shaikh** [comment]
> The type property is public. You can already inspect it.

Hi Taylor, thanks for reviewing the PR. I was building upon the existing filters added in the 'src/IncomingEntry.php' file and added these as they were missing. These filters allow builtin filtering capabilities when using them in the TelescopeServiceProvider. I needed to filter some entries in my application and that's why I added these so others could use it too. 

I am just curious as to why the PRs were closed instead of being merged. Thanks

**Comment by paras-malhotra** [comment]
I think what he meant to say was that you can use `$entry->type === EntryType::COMMAND` directly in your `TelescopeServiceProvider` since `type` is a public property.

**Comment by Ali-Shaikh** [comment]
> I think what he meant to say was that you can use `$entry->type === EntryType::COMMAND` directly in your `TelescopeServiceProvider` since `type` is a public property.

Got it, thanks. I just thought that using isCommand() way is much cleaner and consistent which is why I created the PRs

**Pull request closed without merging**
