### PR TITLE
fix QueryWatcher stack trace collector for closure

### LINKED ISSUE #236: Installation Issue: Undefined index: file
After running `php artisan telescope:install` I ran `php artisan migrate` and this error appeared:

```
vagrant@homestead:~/project$ php artisan migrate

   ErrorException  : Undefined index: file

  at /home/vagrant/project/vendor/laravel/telescope/src/Watchers/QueryWatcher.php:78
    74|     {
    75|         $trace = collect(debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS))->forget(0);
    76| 
    77|         return $trace->first(function ($frame) {
  > 78|             return ! Str::contains($frame['file'],
    79|                 base_path('vendor'.DIRECTORY_SEPARATOR.'laravel')
    80|             );
    81|         });
    82|     }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: file", "/home/vagrant/project/vendor/laravel/telescope/src/Watchers/QueryWatcher.php", [])
      /home/vagrant/project/vendor/laravel/telescope/src/Watchers/QueryWatcher.php:78

  2   Laravel\Telescope\Watchers\QueryWatcher::Laravel\Telescope\Watchers\{closure}(["handle", "Illuminate\Database\Console\Migrations\MigrateCommand", "->"])
      /home/vagrant/project/vendor/laravel/framework/src/Illuminate/Support/Arr.php:175

  Please use the argument -v to see more details.
```

Running the latest version in Laravel Homestead. This is a brand new project. This seems to be caused in v0.1.4 on this line https://github.com/laravel/telescope/compare/v0.1.3...v0.1.4#diff-fa8840834f665959fe3cfa98a78adadcR78

### PR DESCRIPTION
**Pull request by munza**
This would fix #236

### CODE REVIEW

**Comment by drolean** [comment]
i have same problem here, but extend on the lines
https://github.com/munza/telescope/blob/1.0/src/Watchers/QueryWatcher.php#L41
https://github.com/munza/telescope/blob/1.0/src/Watchers/QueryWatcher.php#L42

            'file' => $caller['file'],
            'line' => $caller['line'],

**Comment by munza** [comment]
@drolean, I trying to recreate the error for those 2 lines. Can you please mention for which function call you are receiving the error?

**Comment by drolean** [comment]
@munza working fine now, im added poor code in the QueryWatcher.

my fault :)

**Comment by jpmurray** [comment]
Also, it seems fixed to `dev-master` just not in `0.1.4`, so all good here too!

**Pull request merged**
