### PR TITLE
Add view collector

### LINKED ISSUE #677: Views/Templates watcher
I think View/Template information could be very useful. Do you have plans for this, or are you okay with making a PR for this?

Wouldn't have to be much, but just the views that are rendered (eg view name / actual filename / maybe parameters that are passed or something.

### PR DESCRIPTION
**Pull request by barryvdh**
This adds a Watcher for the Views/templates. 
The RequestWatcher logs the latest view, but not any other views/subviews which might be useful.
The `extractDataFromView` could be re-used, but I think that would generate a lot of data / cost in CPU.
Icon is the same as Model, not sure where the SVG's are coming from to pick one.
Fixes #677
(Assets are not compiled because of potential merge conflicts)

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you screenshot what it looks like?

**Comment by barryvdh** [comment]
I've updated the path to strip the base path, and filters some data that is always present.

Index:
image
Details:
image

Request tab:
image

**Comment by taylorotwell** [comment]
The icons are Zondicons it looks like: https://www.zondicons.com/icons.html

**Comment by taylorotwell** [comment]
Maybe `show-sidebar` icon?

**Comment by barryvdh** [comment]
Sure, updated it.

**Comment by barryvdh** [comment]
Thanks? Don't forget this still needs a compilation of assets.

**Pull request merged**
