### PR TITLE
[4.x] fixed frontend request polling memory leaks

### LINKED ISSUE #1085: Frontend Request Polling Memory Leaks
- Telescope Version: v4.5.1
- Laravel Version: v8.49.0
- PHP Version: v8.0

### Description:
The frontend client does not stop request polling after leaving any watch section.

When i navigate from `Events` to `Jobs` section i expects `Events` request polling to stop but both `Events` and `Jobs` request polling continues.

Screenshot 2021-07-05 at 13 08 40

### Steps To Reproduce:
- goto telescope dashboard
- navigate to `Events`, `Jobs`, `Queries`
- open developer console's network tab

### PR DESCRIPTION
**Pull request by myckhel**
When component sends network request, the network response still gets processed after the initiated component has been unmounted which causes the response to initiate another `checkForNewEntries` request.

Given the screenshot below, duplicate requests were being made after navigating from one watch section to another.
Screenshot 2021-07-05 at 13 08 40
 
This pull request prevents watch component from processing network response after component has been unmounted.

 
- fix #1085

### CODE REVIEW

**Comment by driesvints** [comment]
Prs without a sufficient explanation will be closed.

**Comment by myckhel** [comment]
updated description

**Comment by driesvints** [comment]
Thanks for the pr @myckhel!

**Comment by myckhel** [comment]
Its a lie!!! 😮 
Say GOD? 😮 
giphy

Thanks taylor
Thanks driesvints

**Pull request merged**
